# Generated by Django 3.0.3 on 2020-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200509_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheltuieli',
            name='atasament_cheltuieli',
            field=models.ImageField(blank=True, null=True, upload_to='atasament_cheltuieli'),
        ),
    ]
