# Generated by Django 3.0.3 on 2020-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200604_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheltuieli',
            name='categorie',
            field=models.CharField(choices=[('Cumparaturi', 'Cumparaturi'), ('Masina', 'Masina'), ('Casa', 'Casa'), ('Timp Liber', 'Timp Liber'), ('Diverse', 'Diverse')], default='diverse', max_length=15),
        ),
    ]
