# Generated by Django 3.0.3 on 2020-06-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200604_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheltuieli',
            name='note',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='venituri',
            name='note',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
